server:
  port: 8080
spring:
  application:
    name: pos-gateway
  cloud:
    gateway:
      routes:
        - id: products
          uri: http://localhost:8081/
          predicates:
            - Path=/api/products/**
        - id: carts
          uri: http://localhost:8082/
          predicates:
            - Path=/api/carts/**
        - id: counter
          uri: http://localhost:8083/
          predicates:
            - Path=/api/counter/**
        - id: api
          uri: http://localhost:8084/
          predicates:
            - Path=/api/api/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
