spring:
  application:
    name: pos-delivery
server:
  port: 8085

hibernate:
  dialect: org.hibernate.dialect.H2Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
